generator:
  data-source:
    url: jdbc:mysql://rm-bp10160228z2r90ia.mysql.rds.aliyuncs.com:3306/logistics_storage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: jmy
    password: Qwer1234
  # 模块名
  module-name: logistics.storage
  # 作者
  author: wangLiuJing
  # 代码输出目录
  output-dir: E://mybatis-pluse
  # 表前缀
  table-prefix: logist_
  # 表名
  table-names: logist_store_idempotent
  # 数据库乐观锁版本控制字段
  versionColumnName:
